//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceKolkoKrzyzyk
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk")]
    public interface IGraKolkoKrzyzyk
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/Start", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/StartResponse")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/Start", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuch", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuchResponse")]
        ServiceKolkoKrzyzyk.WykonajRuchResponse WykonajRuch(ServiceKolkoKrzyzyk.WykonajRuchRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuch", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuchResponse")]
        System.Threading.Tasks.Task<ServiceKolkoKrzyzyk.WykonajRuchResponse> WykonajRuchAsync(ServiceKolkoKrzyzyk.WykonajRuchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/SprawdzWygrana", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/SprawdzWygranaResponse")]
        int SprawdzWygrana(int wiersz, int kolumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/SprawdzWygrana", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/SprawdzWygranaResponse")]
        System.Threading.Tasks.Task<int> SprawdzWygranaAsync(int wiersz, int kolumna);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WykonajRuch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WykonajRuchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int wiersz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int kolumna;
        
        public WykonajRuchRequest()
        {
        }
        
        public WykonajRuchRequest(int wiersz, int kolumna)
        {
            this.wiersz = wiersz;
            this.kolumna = kolumna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WykonajRuchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WykonajRuchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool WykonajRuchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int wierszServer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int kolumnaServer;
        
        public WykonajRuchResponse()
        {
        }
        
        public WykonajRuchResponse(bool WykonajRuchResult, int wierszServer, int kolumnaServer)
        {
            this.WykonajRuchResult = WykonajRuchResult;
            this.wierszServer = wierszServer;
            this.kolumnaServer = kolumnaServer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IGraKolkoKrzyzykChannel : ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GraKolkoKrzyzykClient : System.ServiceModel.ClientBase<ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk>, ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GraKolkoKrzyzykClient() : 
                base(GraKolkoKrzyzykClient.GetDefaultBinding(), GraKolkoKrzyzykClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGraKolkoKrzyzyk.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GraKolkoKrzyzykClient(EndpointConfiguration endpointConfiguration) : 
                base(GraKolkoKrzyzykClient.GetBindingForEndpoint(endpointConfiguration), GraKolkoKrzyzykClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GraKolkoKrzyzykClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GraKolkoKrzyzykClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GraKolkoKrzyzykClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GraKolkoKrzyzykClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GraKolkoKrzyzykClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void Start()
        {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync()
        {
            return base.Channel.StartAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceKolkoKrzyzyk.WykonajRuchResponse ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk.WykonajRuch(ServiceKolkoKrzyzyk.WykonajRuchRequest request)
        {
            return base.Channel.WykonajRuch(request);
        }
        
        public bool WykonajRuch(int wiersz, int kolumna, out int wierszServer, out int kolumnaServer)
        {
            ServiceKolkoKrzyzyk.WykonajRuchRequest inValue = new ServiceKolkoKrzyzyk.WykonajRuchRequest();
            inValue.wiersz = wiersz;
            inValue.kolumna = kolumna;
            ServiceKolkoKrzyzyk.WykonajRuchResponse retVal = ((ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk)(this)).WykonajRuch(inValue);
            wierszServer = retVal.wierszServer;
            kolumnaServer = retVal.kolumnaServer;
            return retVal.WykonajRuchResult;
        }
        
        public System.Threading.Tasks.Task<ServiceKolkoKrzyzyk.WykonajRuchResponse> WykonajRuchAsync(ServiceKolkoKrzyzyk.WykonajRuchRequest request)
        {
            return base.Channel.WykonajRuchAsync(request);
        }
        
        public int SprawdzWygrana(int wiersz, int kolumna)
        {
            return base.Channel.SprawdzWygrana(wiersz, kolumna);
        }
        
        public System.Threading.Tasks.Task<int> SprawdzWygranaAsync(int wiersz, int kolumna)
        {
            return base.Channel.SprawdzWygranaAsync(wiersz, kolumna);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGraKolkoKrzyzyk))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGraKolkoKrzyzyk))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/KolkoKrzyzyk_UslugaWCF/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GraKolkoKrzyzykClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGraKolkoKrzyzyk);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GraKolkoKrzyzykClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGraKolkoKrzyzyk);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGraKolkoKrzyzyk,
        }
    }
}
